# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chatgptcont

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mdcregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_33efee2d1f9846fa82109bdd0ec7b66c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_61d954214f0742f08a569ee6afff5793 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mdcregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_33efee2d1f9846fa82109bdd0ec7b66c }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chatgptcont'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_93874f524ed54d73929e953da26e844c }}
        images: 'mdcregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_33efee2d1f9846fa82109bdd0ec7b66c }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'